// Datos de ejemplo para países con información económica
export interface CountryData {
  id: string;
  name: string;
  code: string;
  flag: string;
  currency: string;
  currencySymbol: string;
  devaluationVsUSD: number; // Porcentaje de devaluación en el último año
  devaluationVsEUR: number;
  bigMacIndex: number; // Precio del Big Mac en USD
  monthlyLivingCost: number; // Costo mensual promedio en USD
  rentCost: number;
  foodCost: number;
  transportCost: number;
  entertainmentCost: number;
  trend: 'up' | 'down' | 'stable'; // Tendencia de la moneda
  continent: 'america' | 'europe' | 'asia' | 'africa' | 'oceania';
  highlights: string[];
  riskLevel: 'low' | 'medium' | 'high';
  historicalData: { month: string; rate: number }[];
}

export const countriesData: CountryData[] = [
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'AR',
    flag: '🇦🇷',
    currency: 'ARS',
    currencySymbol: '$',
    devaluationVsUSD: -54.2,
    devaluationVsEUR: -51.8,
    bigMacIndex: 3.75,
    monthlyLivingCost: 650,
    rentCost: 280,
    foodCost: 180,
    transportCost: 45,
    entertainmentCost: 145,
    trend: 'down',
    continent: 'america',
    highlights: ['Buenos Aires', 'Patagonia', 'Mendoza'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 800 },
      { month: 'Feb', rate: 850 },
      { month: 'Mar', rate: 920 },
      { month: 'Abr', rate: 980 },
      { month: 'May', rate: 1050 },
      { month: 'Jun', rate: 1150 },
    ],
  },
  {
    id: 'turkey',
    name: 'Turquía',
    code: 'TR',
    flag: '🇹🇷',
    currency: 'TRY',
    currencySymbol: '₺',
    devaluationVsUSD: -38.5,
    devaluationVsEUR: -35.2,
    bigMacIndex: 2.85,
    monthlyLivingCost: 720,
    rentCost: 320,
    foodCost: 200,
    transportCost: 50,
    entertainmentCost: 150,
    trend: 'down',
    continent: 'europe',
    highlights: ['Estambul', 'Capadocia', 'Antalya'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 28 },
      { month: 'Feb', rate: 29 },
      { month: 'Mar', rate: 31 },
      { month: 'Abr', rate: 32 },
      { month: 'May', rate: 33 },
      { month: 'Jun', rate: 34 },
    ],
  },
  {
    id: 'egypt',
    name: 'Egipto',
    code: 'EG',
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: '£',
    devaluationVsUSD: -45.3,
    devaluationVsEUR: -42.1,
    bigMacIndex: 2.15,
    monthlyLivingCost: 480,
    rentCost: 180,
    foodCost: 150,
    transportCost: 35,
    entertainmentCost: 115,
    trend: 'down',
    continent: 'africa',
    highlights: ['El Cairo', 'Luxor', 'Sharm el-Sheikh'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 30 },
      { month: 'Feb', rate: 35 },
      { month: 'Mar', rate: 42 },
      { month: 'Abr', rate: 47 },
      { month: 'May', rate: 49 },
      { month: 'Jun', rate: 50 },
    ],
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'CO',
    flag: '🇨🇴',
    currency: 'COP',
    currencySymbol: '$',
    devaluationVsUSD: -18.7,
    devaluationVsEUR: -15.4,
    bigMacIndex: 3.25,
    monthlyLivingCost: 850,
    rentCost: 380,
    foodCost: 220,
    transportCost: 55,
    entertainmentCost: 195,
    trend: 'down',
    continent: 'america',
    highlights: ['Medellín', 'Cartagena', 'Bogotá'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 3900 },
      { month: 'Feb', rate: 3950 },
      { month: 'Mar', rate: 4050 },
      { month: 'Abr', rate: 4100 },
      { month: 'May', rate: 4150 },
      { month: 'Jun', rate: 4200 },
    ],
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    code: 'VN',
    flag: '🇻🇳',
    currency: 'VND',
    currencySymbol: '₫',
    devaluationVsUSD: -5.2,
    devaluationVsEUR: -2.1,
    bigMacIndex: 2.95,
    monthlyLivingCost: 720,
    rentCost: 300,
    foodCost: 180,
    transportCost: 60,
    entertainmentCost: 180,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Ho Chi Minh', 'Hanoi', 'Da Nang'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 24200 },
      { month: 'Feb', rate: 24300 },
      { month: 'Mar', rate: 24400 },
      { month: 'Abr', rate: 24500 },
      { month: 'May', rate: 24600 },
      { month: 'Jun', rate: 24800 },
    ],
  },
  {
    id: 'mexico',
    name: 'México',
    code: 'MX',
    flag: '🇲🇽',
    currency: 'MXN',
    currencySymbol: '$',
    devaluationVsUSD: -12.4,
    devaluationVsEUR: -9.8,
    bigMacIndex: 4.15,
    monthlyLivingCost: 1100,
    rentCost: 500,
    foodCost: 280,
    transportCost: 70,
    entertainmentCost: 250,
    trend: 'down',
    continent: 'america',
    highlights: ['CDMX', 'Oaxaca', 'Tulum'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 17.2 },
      { month: 'Feb', rate: 17.5 },
      { month: 'Mar', rate: 17.8 },
      { month: 'Abr', rate: 18.1 },
      { month: 'May', rate: 18.4 },
      { month: 'Jun', rate: 18.8 },
    ],
  },
  {
    id: 'thailand',
    name: 'Tailandia',
    code: 'TH',
    flag: '🇹🇭',
    currency: 'THB',
    currencySymbol: '฿',
    devaluationVsUSD: -8.3,
    devaluationVsEUR: -5.6,
    bigMacIndex: 4.25,
    monthlyLivingCost: 980,
    rentCost: 420,
    foodCost: 250,
    transportCost: 80,
    entertainmentCost: 230,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Bangkok', 'Chiang Mai', 'Phuket'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 34 },
      { month: 'Feb', rate: 34.5 },
      { month: 'Mar', rate: 35 },
      { month: 'Abr', rate: 35.5 },
      { month: 'May', rate: 36 },
      { month: 'Jun', rate: 36.5 },
    ],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    currency: 'IDR',
    currencySymbol: 'Rp',
    devaluationVsUSD: -6.8,
    devaluationVsEUR: -4.2,
    bigMacIndex: 2.65,
    monthlyLivingCost: 890,
    rentCost: 380,
    foodCost: 220,
    transportCost: 70,
    entertainmentCost: 220,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Bali', 'Yakarta', 'Lombok'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 15200 },
      { month: 'Feb', rate: 15350 },
      { month: 'Mar', rate: 15500 },
      { month: 'Abr', rate: 15700 },
      { month: 'May', rate: 15900 },
      { month: 'Jun', rate: 16100 },
    ],
  },
  {
    id: 'south-africa',
    name: 'Sudáfrica',
    code: 'ZA',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencySymbol: 'R',
    devaluationVsUSD: -15.2,
    devaluationVsEUR: -12.5,
    bigMacIndex: 3.45,
    monthlyLivingCost: 920,
    rentCost: 400,
    foodCost: 250,
    transportCost: 65,
    entertainmentCost: 205,
    trend: 'down',
    continent: 'africa',
    highlights: ['Ciudad del Cabo', 'Johannesburgo', 'Kruger'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 18.2 },
      { month: 'Feb', rate: 18.6 },
      { month: 'Mar', rate: 19.1 },
      { month: 'Abr', rate: 19.5 },
      { month: 'May', rate: 19.9 },
      { month: 'Jun', rate: 20.4 },
    ],
  },
  {
    id: 'hungary',
    name: 'Hungría',
    code: 'HU',
    flag: '🇭🇺',
    currency: 'HUF',
    currencySymbol: 'Ft',
    devaluationVsUSD: -22.1,
    devaluationVsEUR: -8.5,
    bigMacIndex: 4.05,
    monthlyLivingCost: 1050,
    rentCost: 480,
    foodCost: 280,
    transportCost: 60,
    entertainmentCost: 230,
    trend: 'down',
    continent: 'europe',
    highlights: ['Budapest', 'Balaton', 'Eger'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 350 },
      { month: 'Feb', rate: 360 },
      { month: 'Mar', rate: 370 },
      { month: 'Abr', rate: 375 },
      { month: 'May', rate: 380 },
      { month: 'Jun', rate: 390 },
    ],
  },
  {
    id: 'brazil',
    name: 'Brasil',
    code: 'BR',
    flag: '🇧🇷',
    currency: 'BRL',
    currencySymbol: 'R$',
    devaluationVsUSD: -16.8,
    devaluationVsEUR: -13.5,
    bigMacIndex: 4.85,
    monthlyLivingCost: 950,
    rentCost: 420,
    foodCost: 260,
    transportCost: 65,
    entertainmentCost: 205,
    trend: 'down',
    continent: 'america',
    highlights: ['Río de Janeiro', 'São Paulo', 'Florianópolis'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 4.9 },
      { month: 'Feb', rate: 5.0 },
      { month: 'Mar', rate: 5.1 },
      { month: 'Abr', rate: 5.2 },
      { month: 'May', rate: 5.4 },
      { month: 'Jun', rate: 5.6 },
    ],
  },
  {
    id: 'philippines',
    name: 'Filipinas',
    code: 'PH',
    flag: '🇵🇭',
    currency: 'PHP',
    currencySymbol: '₱',
    devaluationVsUSD: -9.4,
    devaluationVsEUR: -6.8,
    bigMacIndex: 3.15,
    monthlyLivingCost: 780,
    rentCost: 320,
    foodCost: 200,
    transportCost: 55,
    entertainmentCost: 205,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Manila', 'Cebu', 'Palawan'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 55 },
      { month: 'Feb', rate: 55.5 },
      { month: 'Mar', rate: 56 },
      { month: 'Abr', rate: 56.5 },
      { month: 'May', rate: 57 },
      { month: 'Jun', rate: 58 },
    ],
  },
  {
    id: 'morocco',
    name: 'Marruecos',
    code: 'MA',
    flag: '🇲🇦',
    currency: 'MAD',
    currencySymbol: 'د.م.',
    devaluationVsUSD: -4.2,
    devaluationVsEUR: -1.5,
    bigMacIndex: 3.95,
    monthlyLivingCost: 820,
    rentCost: 350,
    foodCost: 220,
    transportCost: 50,
    entertainmentCost: 200,
    trend: 'stable',
    continent: 'africa',
    highlights: ['Marrakech', 'Fez', 'Casablanca'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 10.1 },
      { month: 'Feb', rate: 10.2 },
      { month: 'Mar', rate: 10.3 },
      { month: 'Abr', rate: 10.4 },
      { month: 'May', rate: 10.5 },
      { month: 'Jun', rate: 10.6 },
    ],
  },
  {
    id: 'poland',
    name: 'Polonia',
    code: 'PL',
    flag: '🇵🇱',
    currency: 'PLN',
    currencySymbol: 'zł',
    devaluationVsUSD: -11.3,
    devaluationVsEUR: -3.2,
    bigMacIndex: 4.35,
    monthlyLivingCost: 1150,
    rentCost: 550,
    foodCost: 280,
    transportCost: 65,
    entertainmentCost: 255,
    trend: 'stable',
    continent: 'europe',
    highlights: ['Cracovia', 'Varsovia', 'Gdansk'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 4.0 },
      { month: 'Feb', rate: 4.05 },
      { month: 'Mar', rate: 4.1 },
      { month: 'Abr', rate: 4.15 },
      { month: 'May', rate: 4.2 },
      { month: 'Jun', rate: 4.3 },
    ],
  },
  {
    id: 'venezuela',
    name: 'Venezuela',
    code: 'VE',
    flag: '🇻🇪',
    currency: 'VES',
    currencySymbol: 'Bs',
    devaluationVsUSD: -95.2,
    devaluationVsEUR: -94.8,
    bigMacIndex: 1.85,
    monthlyLivingCost: 380,
    rentCost: 150,
    foodCost: 120,
    transportCost: 30,
    entertainmentCost: 80,
    trend: 'down',
    continent: 'america',
    highlights: ['Caracas', 'Isla Margarita', 'Los Roques'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 25 },
      { month: 'Feb', rate: 28 },
      { month: 'Mar', rate: 32 },
      { month: 'Abr', rate: 35 },
      { month: 'May', rate: 38 },
      { month: 'Jun', rate: 42 },
    ],
  },
  {
    id: 'lebanon',
    name: 'Líbano',
    code: 'LB',
    flag: '🇱🇧',
    currency: 'LBP',
    currencySymbol: 'ل.ل',
    devaluationVsUSD: -89.5,
    devaluationVsEUR: -88.2,
    bigMacIndex: 2.10,
    monthlyLivingCost: 520,
    rentCost: 220,
    foodCost: 150,
    transportCost: 40,
    entertainmentCost: 110,
    trend: 'down',
    continent: 'asia',
    highlights: ['Beirut', 'Byblos', 'Baalbek'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 85000 },
      { month: 'Feb', rate: 87000 },
      { month: 'Mar', rate: 89000 },
      { month: 'Abr', rate: 90000 },
      { month: 'May', rate: 89500 },
      { month: 'Jun', rate: 89700 },
    ],
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    code: 'LK',
    flag: '🇱🇰',
    currency: 'LKR',
    currencySymbol: 'Rs',
    devaluationVsUSD: -72.4,
    devaluationVsEUR: -70.1,
    bigMacIndex: 2.25,
    monthlyLivingCost: 450,
    rentCost: 180,
    foodCost: 130,
    transportCost: 35,
    entertainmentCost: 105,
    trend: 'down',
    continent: 'asia',
    highlights: ['Colombo', 'Galle', 'Kandy'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 320 },
      { month: 'Feb', rate: 330 },
      { month: 'Mar', rate: 340 },
      { month: 'Abr', rate: 345 },
      { month: 'May', rate: 350 },
      { month: 'Jun', rate: 360 },
    ],
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    code: 'NG',
    flag: '🇳🇬',
    currency: 'NGN',
    currencySymbol: '₦',
    devaluationVsUSD: -68.3,
    devaluationVsEUR: -65.8,
    bigMacIndex: 2.45,
    monthlyLivingCost: 520,
    rentCost: 200,
    foodCost: 160,
    transportCost: 45,
    entertainmentCost: 115,
    trend: 'down',
    continent: 'africa',
    highlights: ['Lagos', 'Abuja', 'Port Harcourt'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 800 },
      { month: 'Feb', rate: 900 },
      { month: 'Mar', rate: 1100 },
      { month: 'Abr', rate: 1250 },
      { month: 'May', rate: 1400 },
      { month: 'Jun', rate: 1500 },
    ],
  },
  {
    id: 'pakistan',
    name: 'Pakistán',
    code: 'PK',
    flag: '🇵🇰',
    currency: 'PKR',
    currencySymbol: '₨',
    devaluationVsUSD: -42.6,
    devaluationVsEUR: -40.2,
    bigMacIndex: 2.35,
    monthlyLivingCost: 420,
    rentCost: 160,
    foodCost: 130,
    transportCost: 35,
    entertainmentCost: 95,
    trend: 'down',
    continent: 'asia',
    highlights: ['Karachi', 'Lahore', 'Islamabad'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 270 },
      { month: 'Feb', rate: 275 },
      { month: 'Mar', rate: 280 },
      { month: 'Abr', rate: 285 },
      { month: 'May', rate: 290 },
      { month: 'Jun', rate: 298 },
    ],
  },
  {
    id: 'ghana',
    name: 'Ghana',
    code: 'GH',
    flag: '🇬🇭',
    currency: 'GHS',
    currencySymbol: '₵',
    devaluationVsUSD: -55.8,
    devaluationVsEUR: -53.2,
    bigMacIndex: 2.55,
    monthlyLivingCost: 580,
    rentCost: 240,
    foodCost: 170,
    transportCost: 50,
    entertainmentCost: 120,
    trend: 'down',
    continent: 'africa',
    highlights: ['Accra', 'Kumasi', 'Cape Coast'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 12 },
      { month: 'Feb', rate: 12.5 },
      { month: 'Mar', rate: 13 },
      { month: 'Abr', rate: 13.5 },
      { month: 'May', rate: 14 },
      { month: 'Jun', rate: 15 },
    ],
  },
  {
    id: 'kenya',
    name: 'Kenia',
    code: 'KE',
    flag: '🇰🇪',
    currency: 'KES',
    currencySymbol: 'KSh',
    devaluationVsUSD: -28.4,
    devaluationVsEUR: -25.8,
    bigMacIndex: 3.05,
    monthlyLivingCost: 680,
    rentCost: 290,
    foodCost: 190,
    transportCost: 55,
    entertainmentCost: 145,
    trend: 'down',
    continent: 'africa',
    highlights: ['Nairobi', 'Mombasa', 'Masái Mara'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 145 },
      { month: 'Feb', rate: 148 },
      { month: 'Mar', rate: 152 },
      { month: 'Abr', rate: 155 },
      { month: 'May', rate: 158 },
      { month: 'Jun', rate: 162 },
    ],
  },
  {
    id: 'ukraine',
    name: 'Ucrania',
    code: 'UA',
    flag: '🇺🇦',
    currency: 'UAH',
    currencySymbol: '₴',
    devaluationVsUSD: -35.2,
    devaluationVsEUR: -32.5,
    bigMacIndex: 2.15,
    monthlyLivingCost: 520,
    rentCost: 220,
    foodCost: 150,
    transportCost: 40,
    entertainmentCost: 110,
    trend: 'down',
    continent: 'europe',
    highlights: ['Lviv', 'Odesa', 'Kyiv'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 36 },
      { month: 'Feb', rate: 37 },
      { month: 'Mar', rate: 38 },
      { month: 'Abr', rate: 39 },
      { month: 'May', rate: 40 },
      { month: 'Jun', rate: 41 },
    ],
  },
  {
    id: 'russia',
    name: 'Rusia',
    code: 'RU',
    flag: '🇷🇺',
    currency: 'RUB',
    currencySymbol: '₽',
    devaluationVsUSD: -32.8,
    devaluationVsEUR: -30.1,
    bigMacIndex: 2.65,
    monthlyLivingCost: 750,
    rentCost: 320,
    foodCost: 200,
    transportCost: 60,
    entertainmentCost: 170,
    trend: 'down',
    continent: 'europe',
    highlights: ['Moscú', 'San Petersburgo', 'Sochi'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 85 },
      { month: 'Feb', rate: 88 },
      { month: 'Mar', rate: 92 },
      { month: 'Abr', rate: 95 },
      { month: 'May', rate: 98 },
      { month: 'Jun', rate: 102 },
    ],
  },
  {
    id: 'japan',
    name: 'Japón',
    code: 'JP',
    flag: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    devaluationVsUSD: -18.5,
    devaluationVsEUR: -15.2,
    bigMacIndex: 3.85,
    monthlyLivingCost: 1450,
    rentCost: 680,
    foodCost: 380,
    transportCost: 120,
    entertainmentCost: 270,
    trend: 'down',
    continent: 'asia',
    highlights: ['Tokio', 'Osaka', 'Kioto'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 145 },
      { month: 'Feb', rate: 148 },
      { month: 'Mar', rate: 152 },
      { month: 'Abr', rate: 155 },
      { month: 'May', rate: 158 },
      { month: 'Jun', rate: 160 },
    ],
  },
  {
    id: 'chile',
    name: 'Chile',
    code: 'CL',
    flag: '🇨🇱',
    currency: 'CLP',
    currencySymbol: '$',
    devaluationVsUSD: -14.2,
    devaluationVsEUR: -11.5,
    bigMacIndex: 4.45,
    monthlyLivingCost: 1050,
    rentCost: 480,
    foodCost: 280,
    transportCost: 70,
    entertainmentCost: 220,
    trend: 'down',
    continent: 'america',
    highlights: ['Santiago', 'Valparaíso', 'Atacama'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 880 },
      { month: 'Feb', rate: 890 },
      { month: 'Mar', rate: 910 },
      { month: 'Abr', rate: 930 },
      { month: 'May', rate: 950 },
      { month: 'Jun', rate: 980 },
    ],
  },
  {
    id: 'peru',
    name: 'Perú',
    code: 'PE',
    flag: '🇵🇪',
    currency: 'PEN',
    currencySymbol: 'S/',
    devaluationVsUSD: -8.5,
    devaluationVsEUR: -5.8,
    bigMacIndex: 3.55,
    monthlyLivingCost: 780,
    rentCost: 340,
    foodCost: 220,
    transportCost: 55,
    entertainmentCost: 165,
    trend: 'stable',
    continent: 'america',
    highlights: ['Lima', 'Cusco', 'Arequipa'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 3.7 },
      { month: 'Feb', rate: 3.72 },
      { month: 'Mar', rate: 3.75 },
      { month: 'Abr', rate: 3.78 },
      { month: 'May', rate: 3.8 },
      { month: 'Jun', rate: 3.82 },
    ],
  },
  {
    id: 'czech',
    name: 'República Checa',
    code: 'CZ',
    flag: '🇨🇿',
    currency: 'CZK',
    currencySymbol: 'Kč',
    devaluationVsUSD: -15.3,
    devaluationVsEUR: -4.8,
    bigMacIndex: 4.65,
    monthlyLivingCost: 1180,
    rentCost: 560,
    foodCost: 300,
    transportCost: 70,
    entertainmentCost: 250,
    trend: 'stable',
    continent: 'europe',
    highlights: ['Praga', 'Brno', 'Český Krumlov'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 22 },
      { month: 'Feb', rate: 22.5 },
      { month: 'Mar', rate: 23 },
      { month: 'Abr', rate: 23.3 },
      { month: 'May', rate: 23.5 },
      { month: 'Jun', rate: 24 },
    ],
  },
  {
    id: 'romania',
    name: 'Rumania',
    code: 'RO',
    flag: '🇷🇴',
    currency: 'RON',
    currencySymbol: 'lei',
    devaluationVsUSD: -12.8,
    devaluationVsEUR: -2.5,
    bigMacIndex: 3.25,
    monthlyLivingCost: 920,
    rentCost: 420,
    foodCost: 250,
    transportCost: 55,
    entertainmentCost: 195,
    trend: 'stable',
    continent: 'europe',
    highlights: ['Bucarest', 'Brasov', 'Cluj-Napoca'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 4.5 },
      { month: 'Feb', rate: 4.55 },
      { month: 'Mar', rate: 4.6 },
      { month: 'Abr', rate: 4.62 },
      { month: 'May', rate: 4.65 },
      { month: 'Jun', rate: 4.7 },
    ],
  },
  {
    id: 'india',
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    devaluationVsUSD: -10.2,
    devaluationVsEUR: -7.5,
    bigMacIndex: 2.55,
    monthlyLivingCost: 550,
    rentCost: 220,
    foodCost: 160,
    transportCost: 45,
    entertainmentCost: 125,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Delhi', 'Mumbai', 'Goa'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 82 },
      { month: 'Feb', rate: 82.5 },
      { month: 'Mar', rate: 83 },
      { month: 'Abr', rate: 83.2 },
      { month: 'May', rate: 83.5 },
      { month: 'Jun', rate: 84 },
    ],
  },
  {
    id: 'malaysia',
    name: 'Malasia',
    code: 'MY',
    flag: '🇲🇾',
    currency: 'MYR',
    currencySymbol: 'RM',
    devaluationVsUSD: -11.8,
    devaluationVsEUR: -9.2,
    bigMacIndex: 2.85,
    monthlyLivingCost: 820,
    rentCost: 350,
    foodCost: 220,
    transportCost: 60,
    entertainmentCost: 190,
    trend: 'down',
    continent: 'asia',
    highlights: ['Kuala Lumpur', 'Penang', 'Langkawi'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 4.4 },
      { month: 'Feb', rate: 4.45 },
      { month: 'Mar', rate: 4.5 },
      { month: 'Abr', rate: 4.55 },
      { month: 'May', rate: 4.6 },
      { month: 'Jun', rate: 4.7 },
    ],
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    code: 'BD',
    flag: '🇧🇩',
    currency: 'BDT',
    currencySymbol: '৳',
    devaluationVsUSD: -25.6,
    devaluationVsEUR: -22.8,
    bigMacIndex: 2.15,
    monthlyLivingCost: 380,
    rentCost: 140,
    foodCost: 120,
    transportCost: 30,
    entertainmentCost: 90,
    trend: 'down',
    continent: 'asia',
    highlights: ['Dhaka', 'Cox\'s Bazar', 'Sylhet'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 105 },
      { month: 'Feb', rate: 108 },
      { month: 'Mar', rate: 110 },
      { month: 'Abr', rate: 112 },
      { month: 'May', rate: 115 },
      { month: 'Jun', rate: 118 },
    ],
  },
  {
    id: 'ethiopia',
    name: 'Etiopía',
    code: 'ET',
    flag: '🇪🇹',
    currency: 'ETB',
    currencySymbol: 'Br',
    devaluationVsUSD: -48.5,
    devaluationVsEUR: -45.8,
    bigMacIndex: 1.95,
    monthlyLivingCost: 420,
    rentCost: 160,
    foodCost: 140,
    transportCost: 35,
    entertainmentCost: 85,
    trend: 'down',
    continent: 'africa',
    highlights: ['Addis Abeba', 'Lalibela', 'Gondar'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 55 },
      { month: 'Feb', rate: 58 },
      { month: 'Mar', rate: 62 },
      { month: 'Abr', rate: 68 },
      { month: 'May', rate: 75 },
      { month: 'Jun', rate: 85 },
    ],
  },
  {
    id: 'cambodia',
    name: 'Camboya',
    code: 'KH',
    flag: '🇰🇭',
    currency: 'KHR',
    currencySymbol: '៛',
    devaluationVsUSD: -3.2,
    devaluationVsEUR: -0.8,
    bigMacIndex: 2.75,
    monthlyLivingCost: 650,
    rentCost: 280,
    foodCost: 180,
    transportCost: 50,
    entertainmentCost: 140,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Phnom Penh', 'Siem Reap', 'Sihanoukville'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 4050 },
      { month: 'Feb', rate: 4060 },
      { month: 'Mar', rate: 4070 },
      { month: 'Abr', rate: 4080 },
      { month: 'May', rate: 4090 },
      { month: 'Jun', rate: 4100 },
    ],
  },
  {
    id: 'nepal',
    name: 'Nepal',
    code: 'NP',
    flag: '🇳🇵',
    currency: 'NPR',
    currencySymbol: 'रू',
    devaluationVsUSD: -10.8,
    devaluationVsEUR: -8.2,
    bigMacIndex: 2.25,
    monthlyLivingCost: 480,
    rentCost: 180,
    foodCost: 150,
    transportCost: 40,
    entertainmentCost: 110,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Katmandú', 'Pokhara', 'Everest'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 132 },
      { month: 'Feb', rate: 133 },
      { month: 'Mar', rate: 134 },
      { month: 'Abr', rate: 134.5 },
      { month: 'May', rate: 135 },
      { month: 'Jun', rate: 136 },
    ],
  },
  {
    id: 'laos',
    name: 'Laos',
    code: 'LA',
    flag: '🇱🇦',
    currency: 'LAK',
    currencySymbol: '₭',
    devaluationVsUSD: -58.4,
    devaluationVsEUR: -55.8,
    bigMacIndex: 2.35,
    monthlyLivingCost: 520,
    rentCost: 200,
    foodCost: 160,
    transportCost: 45,
    entertainmentCost: 115,
    trend: 'down',
    continent: 'asia',
    highlights: ['Vientián', 'Luang Prabang', 'Vang Vieng'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 18000 },
      { month: 'Feb', rate: 18500 },
      { month: 'Mar', rate: 19000 },
      { month: 'Abr', rate: 19500 },
      { month: 'May', rate: 20000 },
      { month: 'Jun', rate: 21000 },
    ],
  },
  {
    id: 'costa-rica',
    name: 'Costa Rica',
    code: 'CR',
    flag: '🇨🇷',
    currency: 'CRC',
    currencySymbol: '₡',
    devaluationVsUSD: -6.5,
    devaluationVsEUR: -3.8,
    bigMacIndex: 4.85,
    monthlyLivingCost: 1280,
    rentCost: 580,
    foodCost: 350,
    transportCost: 80,
    entertainmentCost: 270,
    trend: 'stable',
    continent: 'america',
    highlights: ['San José', 'Manuel Antonio', 'Monteverde'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 520 },
      { month: 'Feb', rate: 525 },
      { month: 'Mar', rate: 530 },
      { month: 'Abr', rate: 535 },
      { month: 'May', rate: 540 },
      { month: 'Jun', rate: 545 },
    ],
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    code: 'UY',
    flag: '🇺🇾',
    currency: 'UYU',
    currencySymbol: '$U',
    devaluationVsUSD: -9.2,
    devaluationVsEUR: -6.5,
    bigMacIndex: 5.25,
    monthlyLivingCost: 1380,
    rentCost: 620,
    foodCost: 380,
    transportCost: 85,
    entertainmentCost: 295,
    trend: 'stable',
    continent: 'america',
    highlights: ['Montevideo', 'Punta del Este', 'Colonia'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 38 },
      { month: 'Feb', rate: 38.5 },
      { month: 'Mar', rate: 39 },
      { month: 'Abr', rate: 39.5 },
      { month: 'May', rate: 40 },
      { month: 'Jun', rate: 40.5 },
    ],
  },
];

// Países de referencia (origen del usuario)
export interface ReferenceCountry {
  id: string;
  name: string;
  code: string;
  flag: string;
  currency: string;
  avgMonthlyIncome: number; // Ingreso promedio mensual en USD
}

export const referenceCountries: ReferenceCountry[] = [
  { id: 'usa', name: 'Estados Unidos', code: 'US', flag: '🇺🇸', currency: 'USD', avgMonthlyIncome: 4500 },
  { id: 'spain', name: 'España', code: 'ES', flag: '🇪🇸', currency: 'EUR', avgMonthlyIncome: 2200 },
  { id: 'germany', name: 'Alemania', code: 'DE', flag: '🇩🇪', currency: 'EUR', avgMonthlyIncome: 3200 },
  { id: 'france', name: 'Francia', code: 'FR', flag: '🇫🇷', currency: 'EUR', avgMonthlyIncome: 2600 },
  { id: 'uk', name: 'Reino Unido', code: 'GB', flag: '🇬🇧', currency: 'GBP', avgMonthlyIncome: 3000 },
  { id: 'canada', name: 'Canadá', code: 'CA', flag: '🇨🇦', currency: 'CAD', avgMonthlyIncome: 3500 },
  { id: 'australia', name: 'Australia', code: 'AU', flag: '🇦🇺', currency: 'AUD', avgMonthlyIncome: 4000 },
  { id: 'switzerland', name: 'Suiza', code: 'CH', flag: '🇨🇭', currency: 'CHF', avgMonthlyIncome: 5500 },
];

// Función para calcular el poder adquisitivo
export const calculatePurchasingPower = (
  originIncome: number,
  destinationCost: number
): number => {
  return Math.round((originIncome / destinationCost) * 100) / 100;
};

// Función para ordenar países por oportunidad
export const sortByOpportunity = (countries: CountryData[]): CountryData[] => {
  return [...countries].sort((a, b) => {
    // Combinar devaluación alta + costo bajo = mejor oportunidad
    const scoreA = Math.abs(a.devaluationVsUSD) * 0.5 + (1000 - a.monthlyLivingCost) * 0.05;
    const scoreB = Math.abs(b.devaluationVsUSD) * 0.5 + (1000 - b.monthlyLivingCost) * 0.05;
    return scoreB - scoreA;
  });
};
