// Datos de ejemplo para países con información económica
export interface CountryData {
  id: string;
  name: string;
  code: string;
  flag: string;
  currency: string;
  currencySymbol: string;
  devaluationVsUSD: number; // Porcentaje de devaluación en el último año
  devaluationVsEUR: number;
  bigMacIndex: number; // Precio del Big Mac en USD
  monthlyLivingCost: number; // Costo mensual promedio en USD
  rentCost: number;
  foodCost: number;
  transportCost: number;
  entertainmentCost: number;
  trend: 'up' | 'down' | 'stable'; // Tendencia de la moneda
  continent: 'america' | 'europe' | 'asia' | 'africa' | 'oceania';
  highlights: string[];
  riskLevel: 'low' | 'medium' | 'high';
  historicalData: { month: string; rate: number }[];
}

export const countriesData: CountryData[] = [
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'AR',
    flag: '🇦🇷',
    currency: 'ARS',
    currencySymbol: '$',
    devaluationVsUSD: -54.2,
    devaluationVsEUR: -51.8,
    bigMacIndex: 3.75,
    monthlyLivingCost: 650,
    rentCost: 280,
    foodCost: 180,
    transportCost: 45,
    entertainmentCost: 145,
    trend: 'down',
    continent: 'america',
    highlights: ['Buenos Aires', 'Patagonia', 'Mendoza'],
    riskLevel: 'high',
    historicalData: [
      { month: 'Ene', rate: 800 },
      { month: 'Feb', rate: 850 },
      { month: 'Mar', rate: 920 },
      { month: 'Abr', rate: 980 },
      { month: 'May', rate: 1050 },
      { month: 'Jun', rate: 1150 },
    ],
  },
  {
    id: 'turkey',
    name: 'Turquía',
    code: 'TR',
    flag: '🇹🇷',
    currency: 'TRY',
    currencySymbol: '₺',
    devaluationVsUSD: -38.5,
    devaluationVsEUR: -35.2,
    bigMacIndex: 2.85,
    monthlyLivingCost: 720,
    rentCost: 320,
    foodCost: 200,
    transportCost: 50,
    entertainmentCost: 150,
    trend: 'down',
    continent: 'europe',
    highlights: ['Estambul', 'Capadocia', 'Antalya'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 28 },
      { month: 'Feb', rate: 29 },
      { month: 'Mar', rate: 31 },
      { month: 'Abr', rate: 32 },
      { month: 'May', rate: 33 },
      { month: 'Jun', rate: 34 },
    ],
  },
  {
    id: 'egypt',
    name: 'Egipto',
    code: 'EG',
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: '£',
    devaluationVsUSD: -45.3,
    devaluationVsEUR: -42.1,
    bigMacIndex: 2.15,
    monthlyLivingCost: 480,
    rentCost: 180,
    foodCost: 150,
    transportCost: 35,
    entertainmentCost: 115,
    trend: 'down',
    continent: 'africa',
    highlights: ['El Cairo', 'Luxor', 'Sharm el-Sheikh'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 30 },
      { month: 'Feb', rate: 35 },
      { month: 'Mar', rate: 42 },
      { month: 'Abr', rate: 47 },
      { month: 'May', rate: 49 },
      { month: 'Jun', rate: 50 },
    ],
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'CO',
    flag: '🇨🇴',
    currency: 'COP',
    currencySymbol: '$',
    devaluationVsUSD: -18.7,
    devaluationVsEUR: -15.4,
    bigMacIndex: 3.25,
    monthlyLivingCost: 850,
    rentCost: 380,
    foodCost: 220,
    transportCost: 55,
    entertainmentCost: 195,
    trend: 'down',
    continent: 'america',
    highlights: ['Medellín', 'Cartagena', 'Bogotá'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 3900 },
      { month: 'Feb', rate: 3950 },
      { month: 'Mar', rate: 4050 },
      { month: 'Abr', rate: 4100 },
      { month: 'May', rate: 4150 },
      { month: 'Jun', rate: 4200 },
    ],
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    code: 'VN',
    flag: '🇻🇳',
    currency: 'VND',
    currencySymbol: '₫',
    devaluationVsUSD: -5.2,
    devaluationVsEUR: -2.1,
    bigMacIndex: 2.95,
    monthlyLivingCost: 720,
    rentCost: 300,
    foodCost: 180,
    transportCost: 60,
    entertainmentCost: 180,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Ho Chi Minh', 'Hanoi', 'Da Nang'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 24200 },
      { month: 'Feb', rate: 24300 },
      { month: 'Mar', rate: 24400 },
      { month: 'Abr', rate: 24500 },
      { month: 'May', rate: 24600 },
      { month: 'Jun', rate: 24800 },
    ],
  },
  {
    id: 'mexico',
    name: 'México',
    code: 'MX',
    flag: '🇲🇽',
    currency: 'MXN',
    currencySymbol: '$',
    devaluationVsUSD: -12.4,
    devaluationVsEUR: -9.8,
    bigMacIndex: 4.15,
    monthlyLivingCost: 1100,
    rentCost: 500,
    foodCost: 280,
    transportCost: 70,
    entertainmentCost: 250,
    trend: 'down',
    continent: 'america',
    highlights: ['CDMX', 'Oaxaca', 'Tulum'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 17.2 },
      { month: 'Feb', rate: 17.5 },
      { month: 'Mar', rate: 17.8 },
      { month: 'Abr', rate: 18.1 },
      { month: 'May', rate: 18.4 },
      { month: 'Jun', rate: 18.8 },
    ],
  },
  {
    id: 'thailand',
    name: 'Tailandia',
    code: 'TH',
    flag: '🇹🇭',
    currency: 'THB',
    currencySymbol: '฿',
    devaluationVsUSD: -8.3,
    devaluationVsEUR: -5.6,
    bigMacIndex: 4.25,
    monthlyLivingCost: 980,
    rentCost: 420,
    foodCost: 250,
    transportCost: 80,
    entertainmentCost: 230,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Bangkok', 'Chiang Mai', 'Phuket'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 34 },
      { month: 'Feb', rate: 34.5 },
      { month: 'Mar', rate: 35 },
      { month: 'Abr', rate: 35.5 },
      { month: 'May', rate: 36 },
      { month: 'Jun', rate: 36.5 },
    ],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    currency: 'IDR',
    currencySymbol: 'Rp',
    devaluationVsUSD: -6.8,
    devaluationVsEUR: -4.2,
    bigMacIndex: 2.65,
    monthlyLivingCost: 890,
    rentCost: 380,
    foodCost: 220,
    transportCost: 70,
    entertainmentCost: 220,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Bali', 'Yakarta', 'Lombok'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 15200 },
      { month: 'Feb', rate: 15350 },
      { month: 'Mar', rate: 15500 },
      { month: 'Abr', rate: 15700 },
      { month: 'May', rate: 15900 },
      { month: 'Jun', rate: 16100 },
    ],
  },
  {
    id: 'south-africa',
    name: 'Sudáfrica',
    code: 'ZA',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencySymbol: 'R',
    devaluationVsUSD: -15.2,
    devaluationVsEUR: -12.5,
    bigMacIndex: 3.45,
    monthlyLivingCost: 920,
    rentCost: 400,
    foodCost: 250,
    transportCost: 65,
    entertainmentCost: 205,
    trend: 'down',
    continent: 'africa',
    highlights: ['Ciudad del Cabo', 'Johannesburgo', 'Kruger'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 18.2 },
      { month: 'Feb', rate: 18.6 },
      { month: 'Mar', rate: 19.1 },
      { month: 'Abr', rate: 19.5 },
      { month: 'May', rate: 19.9 },
      { month: 'Jun', rate: 20.4 },
    ],
  },
  {
    id: 'hungary',
    name: 'Hungría',
    code: 'HU',
    flag: '🇭🇺',
    currency: 'HUF',
    currencySymbol: 'Ft',
    devaluationVsUSD: -22.1,
    devaluationVsEUR: -8.5,
    bigMacIndex: 4.05,
    monthlyLivingCost: 1050,
    rentCost: 480,
    foodCost: 280,
    transportCost: 60,
    entertainmentCost: 230,
    trend: 'down',
    continent: 'europe',
    highlights: ['Budapest', 'Balaton', 'Eger'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 350 },
      { month: 'Feb', rate: 360 },
      { month: 'Mar', rate: 370 },
      { month: 'Abr', rate: 375 },
      { month: 'May', rate: 380 },
      { month: 'Jun', rate: 390 },
    ],
  },
  {
    id: 'brazil',
    name: 'Brasil',
    code: 'BR',
    flag: '🇧🇷',
    currency: 'BRL',
    currencySymbol: 'R$',
    devaluationVsUSD: -16.8,
    devaluationVsEUR: -13.5,
    bigMacIndex: 4.85,
    monthlyLivingCost: 950,
    rentCost: 420,
    foodCost: 260,
    transportCost: 65,
    entertainmentCost: 205,
    trend: 'down',
    continent: 'america',
    highlights: ['Río de Janeiro', 'São Paulo', 'Florianópolis'],
    riskLevel: 'medium',
    historicalData: [
      { month: 'Ene', rate: 4.9 },
      { month: 'Feb', rate: 5.0 },
      { month: 'Mar', rate: 5.1 },
      { month: 'Abr', rate: 5.2 },
      { month: 'May', rate: 5.4 },
      { month: 'Jun', rate: 5.6 },
    ],
  },
  {
    id: 'philippines',
    name: 'Filipinas',
    code: 'PH',
    flag: '🇵🇭',
    currency: 'PHP',
    currencySymbol: '₱',
    devaluationVsUSD: -9.4,
    devaluationVsEUR: -6.8,
    bigMacIndex: 3.15,
    monthlyLivingCost: 780,
    rentCost: 320,
    foodCost: 200,
    transportCost: 55,
    entertainmentCost: 205,
    trend: 'stable',
    continent: 'asia',
    highlights: ['Manila', 'Cebu', 'Palawan'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 55 },
      { month: 'Feb', rate: 55.5 },
      { month: 'Mar', rate: 56 },
      { month: 'Abr', rate: 56.5 },
      { month: 'May', rate: 57 },
      { month: 'Jun', rate: 58 },
    ],
  },
  {
    id: 'morocco',
    name: 'Marruecos',
    code: 'MA',
    flag: '🇲🇦',
    currency: 'MAD',
    currencySymbol: 'د.م.',
    devaluationVsUSD: -4.2,
    devaluationVsEUR: -1.5,
    bigMacIndex: 3.95,
    monthlyLivingCost: 820,
    rentCost: 350,
    foodCost: 220,
    transportCost: 50,
    entertainmentCost: 200,
    trend: 'stable',
    continent: 'africa',
    highlights: ['Marrakech', 'Fez', 'Casablanca'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 10.1 },
      { month: 'Feb', rate: 10.2 },
      { month: 'Mar', rate: 10.3 },
      { month: 'Abr', rate: 10.4 },
      { month: 'May', rate: 10.5 },
      { month: 'Jun', rate: 10.6 },
    ],
  },
  {
    id: 'poland',
    name: 'Polonia',
    code: 'PL',
    flag: '🇵🇱',
    currency: 'PLN',
    currencySymbol: 'zł',
    devaluationVsUSD: -11.3,
    devaluationVsEUR: -3.2,
    bigMacIndex: 4.35,
    monthlyLivingCost: 1150,
    rentCost: 550,
    foodCost: 280,
    transportCost: 65,
    entertainmentCost: 255,
    trend: 'stable',
    continent: 'europe',
    highlights: ['Cracovia', 'Varsovia', 'Gdansk'],
    riskLevel: 'low',
    historicalData: [
      { month: 'Ene', rate: 4.0 },
      { month: 'Feb', rate: 4.05 },
      { month: 'Mar', rate: 4.1 },
      { month: 'Abr', rate: 4.15 },
      { month: 'May', rate: 4.2 },
      { month: 'Jun', rate: 4.3 },
    ],
  },
];

// Países de referencia (origen del usuario)
export interface ReferenceCountry {
  id: string;
  name: string;
  code: string;
  flag: string;
  currency: string;
  avgMonthlyIncome: number; // Ingreso promedio mensual en USD
}

export const referenceCountries: ReferenceCountry[] = [
  { id: 'usa', name: 'Estados Unidos', code: 'US', flag: '🇺🇸', currency: 'USD', avgMonthlyIncome: 4500 },
  { id: 'spain', name: 'España', code: 'ES', flag: '🇪🇸', currency: 'EUR', avgMonthlyIncome: 2200 },
  { id: 'germany', name: 'Alemania', code: 'DE', flag: '🇩🇪', currency: 'EUR', avgMonthlyIncome: 3200 },
  { id: 'france', name: 'Francia', code: 'FR', flag: '🇫🇷', currency: 'EUR', avgMonthlyIncome: 2600 },
  { id: 'uk', name: 'Reino Unido', code: 'GB', flag: '🇬🇧', currency: 'GBP', avgMonthlyIncome: 3000 },
  { id: 'canada', name: 'Canadá', code: 'CA', flag: '🇨🇦', currency: 'CAD', avgMonthlyIncome: 3500 },
  { id: 'australia', name: 'Australia', code: 'AU', flag: '🇦🇺', currency: 'AUD', avgMonthlyIncome: 4000 },
  { id: 'switzerland', name: 'Suiza', code: 'CH', flag: '🇨🇭', currency: 'CHF', avgMonthlyIncome: 5500 },
];

// Función para calcular el poder adquisitivo
export const calculatePurchasingPower = (
  originIncome: number,
  destinationCost: number
): number => {
  return Math.round((originIncome / destinationCost) * 100) / 100;
};

// Función para ordenar países por oportunidad
export const sortByOpportunity = (countries: CountryData[]): CountryData[] => {
  return [...countries].sort((a, b) => {
    // Combinar devaluación alta + costo bajo = mejor oportunidad
    const scoreA = Math.abs(a.devaluationVsUSD) * 0.5 + (1000 - a.monthlyLivingCost) * 0.05;
    const scoreB = Math.abs(b.devaluationVsUSD) * 0.5 + (1000 - b.monthlyLivingCost) * 0.05;
    return scoreB - scoreA;
  });
};
